catalog/urls.py
from django.urls import path
from . import views

# ListView et DetailView sont des classes dans catalog/views.py
urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    # int (integer) : pk (primary key)
    # Ici le paramètre doit porter le nom "pk" vu l'usage d'un générique,
    # mais pourrait porter tout autre nom choise, ou même aucun nom
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    # Liens pour les auteurs
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowedbooks/', views.LoanedBooksListView.as_view(), name='borrowed-books'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('book/<uuid:pk>/loan/', views.loan_book_librarian, name='loan-book-librarian'),
]

librairie_claing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
# Use static() to add url mapping to serve static files during development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Pour charger les hyperliens de l'application catalog
    path('catalog/', include('catalog.urls')),
    # Pour rediriger la racine du site au catalog
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
# Used to generate URLs by reversing the URL patterns
from django.urls import reverse
from django.contrib.auth.models import User
# Required for unique book instances
import uuid
from datetime import date


class Section(models.Model):
    name = models.CharField(
            unique=True,
            max_length=100,
            help_text="Section principale",
            )

    def __str__(self):
        return self.name

    class meta:
        ordering = ['name']


class Subsection(models.Model):
    name = models.CharField(
            unique=True,
            max_length=100,
            help_text="Sous-section",
            )

    def __str__(self):
        return self.name

    class meta:
        ordering = ['name']
        verbose_name = "Sous-section"


class Category(models.Model):
    section = models.ForeignKey(
            Section,
            unique=False,
            related_name='section',
            on_delete=models.CASCADE,
            null=False,
            verbose_name="Section",
            )
    subsection = models.ForeignKey(
            Subsection,
            unique=False,
            related_name='subsection',
            on_delete=models.CASCADE,
            null=True,
            verbose_name="Sous-Section",
            )
    number = models.IntegerField(unique=True)

    def __str__(self):
        number = self.number
        section = self.section.name
        try:
            subsection = self.subsection.name
        except AttributeError:
            subsection = ''
        return "{} / {} / {}".format(
                number,
                section,
                subsection)

    class meta:
        ordering = ['section.name', 'subsection.name']
        verbose_name = "Catégorie"


# Les auteurs
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(
            "Prénom",
            max_length=100,
            null=True,
            )
    last_name = models.CharField(
            "Nom",
            max_length=100,
            db_index=True,
            )
    code = models.CharField(
            "Code",
            max_length=4)
    date_of_birth = models.DateField(
            "Naissance",
            null=True,
            blank=True)
    date_of_death = models.DateField(
            "Décès",
            null=True,
            blank=True)
    hyper = models.URLField(
            "Hyperlien",
            max_length=200,
            blank=True,
            null=True,
            unique=False)

    class Meta:
        ordering = ['last_name', 'first_name']
        verbose_name = 'Auteur'

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def get_delete_url(self):
        """Returns the url to delete a particular author instance."""
        return reverse('author-delete', args=[str(self.id)])

    def get_update_url(self):
        """Returns the url to update a particular author instance."""
        return reverse('author-update', args=[str(self.id)])


# Représentation d'un livre
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(
            max_length=200,
            db_index=True,
            )
    # Foreign Key puisque chaque livre peut avoir plus
    # d'un auteur, et chaque auteur plus d'un livre
    author = models.ForeignKey(
            Author,
            related_name='books',
            on_delete=models.SET_NULL,
            null=True,
            verbose_name="Auteur",)
    summary = models.TextField(
            "Sommaire",
            max_length=1000,
            help_text='Une courte description du livre',
            blank=True,
            )
    isbn = models.CharField(
            'ISBN',
            max_length=13,
            #  unique=True,
            help_text='13 Character <a href="https://www.' +
            'isbn-international.org/content/what-isbn"> ' +
            'ISBN number</a>')
    section = models.ForeignKey(
            Section,
            related_name='sec',
            on_delete=models.SET_NULL,
            null=True,
            verbose_name='Section')
    subsection = models.ForeignKey(
            Subsection,
            related_name='subsec',
            on_delete=models.SET_NULL,
            null=True,
            verbose_name='Subsection')
    # category = models.ForeignKey(
    #         Category,
    #         related_name='category',
    #         on_delete=models.SET_NULL,
    #         null=True,
    #         verbose_name='Catégorie')
    apprenti = models.BooleanField(
            null=True,)
    compagnon = models.BooleanField(
            null=True,)
    maitre = models.BooleanField(
            null=True,)

    class Meta:
        ordering = ['title']
        verbose_name = 'Livre'

    def __str__(self):
        """String for representing the Model object."""
        return str(self.title)

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_cote(self):
        """String cote dans Admin."""
        cote = "{}-{}".format(self.category.number, self.author.code)
        return cote

    display_cote.short_description = 'Cote'


# Exemplaire physique d'un livre et son statut
class BookInstance(models.Model):
    """Model representing a specific copy of
    a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(
                primary_key=True,
                default=uuid.uuid4,
                help_text='Identifiant unique',)
    book = models.ForeignKey(
                    'Book',
                    on_delete=models.RESTRICT,
                    verbose_name="Livre",
                    null=True)
    seq = models.IntegerField(unique=True,)
    don = models.BooleanField(null=True,)
    new = models.BooleanField(null=True,)
    imprint = models.CharField("Édition", max_length=200)
    due_back = models.DateField("Date de retour", null=True, blank=True)
    borrower = models.ForeignKey(
                User,
                on_delete=models.SET_NULL,
                verbose_name="Emprunteur",
                null=True, blank=True)
    comment = models.CharField(null=True, max_length=200)

    BOOK_STATUS = (
        ('i', 'Inactif'),
        ('p', 'Prêté'),
        ('d', 'Disponible'),
        ('r', 'Reservé'),
        ('a', 'À Vendre'),
        ('v', 'Vendu'),
    )

    status = models.CharField(
        max_length=1,
        choices=BOOK_STATUS,
        blank=True,
        default='d',
        help_text="Disponibilité de l'exemplaire",
    )

    class Meta:
        verbose_name = "Exemplaire"
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set Book as returned"), )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title}, {self.status})'

    def display_title(self):
        """Create a string for the instance title.
        This is required to display title in Admin."""
        return self.book.title

    display_title.short_description = 'Titre'

    def display_return(self):
        """Create a string for the instance return date."""
        return self.due_back

    display_return.short_description = 'Date de retour'

    def display_status(self):
        """Create a string for the instance status."""
        loan_dict = {
                'm': 'Maintenance',
                'p': 'Prêt',
                'd': 'Disponible',
                'r': 'Reservé',
                'a': 'À Vendre',
                'v': 'Vendu',
            }
        s = self.status
        status = loan_dict[s]
        return status

    display_status.short_description = 'Statut'


class BookComment(models.Model):
    """Model representing a User about a book"""
    id = models.UUIDField(
            primary_key=True,
            default=uuid.uuid4,
            help_text='Unique ID for this comment')
    book = models.ForeignKey(
            'Book',
            on_delete=models.RESTRICT,
            null=True,
            verbose_name="Livre")
    writer = models.ForeignKey(
                User,
                on_delete=models.SET_NULL,
                verbose_name="Rédacteur",
                null=True)
    text = models.TextField("Commentaire")

    class Meta:
        verbose_name = "Commentaire"
        ordering = ['writer']

    def __str__(self):
        return f'{self.id}, {self.book.title}, {self.text}'

    def display_book(self):
        return self.book.title

    display_book.short_description = 'Titre'

    def display_writer_lname(self):
        return self.writer.last_name

    display_writer_lname.short_description = 'Nom'

    def display_writer_fname(self):
        return self.writer.first_name

    display_writer_fname.short_description = 'Prénom'

catalog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class LoanBookForm(forms.Form):
    return_date = forms.DateField(
            help_text="Date entre aujourd'hui et 4 semamines (défaut 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Date antérieure invalide'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                    _('Date passée 4 semaines'))

        # Remember to always return the cleaned data.
        return data


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
            help_text="Date entre aujourd'hui et 4 semamines (défaut 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Date antérieure invalide'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                    _('Date passée 4 semaines'))

        # Remember to always return the cleaned data.
        return data

# from .models import Book, Category

# class BookListForm(forms.ModelForm):
#     class Meta:
#         model = Book
#         fields = '__all__'

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['category'].queryset = Category.objects.none()

#         if 'section' in self.data:
#             try:
#                 country_id = int(self.data.get(''))
#                 self.fields['city'].queryset = City.objects.filter(country_id=country_id).order_by('name')
#             except (ValueError, TypeError):
#                 pass  # invalid input from the client; ignore and fallback to empty City queryset
#         elif self.instance.pk:
#             self.fields['city'].queryset = self.instance.country.city_set.order_by('name')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Auteur: {{ author.last_name }}, {{ author.first_name }}</h1>
  {% if author.date_of_birth and author.date_of_death %}
    <p> {{author.date_of_birth}} - {{author.date_of_death}} </p>
  {% elif author.date_of_birth and not author.date_of_death %}
    <p> {{author.date_of_birth}} - </p>
  {% endif %}
  <p> <a href="{{author.hyper}}">{{author.hyper}}</a></p>
  <p> <a href="{{author.get_delete_url}}">Effacer</a> - 
  <a href="{{author.get_update_url}}">Modifier</a></p>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Livres</h4>

    {% for book in books %}
      <hr>
      <p> <a href="{{book.get_absolute_url}}">{{book.title}}</a></p>
      <p>{{book.summary}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste des Auteurs</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
	      {% if author.date_of_birth and author.date_of_death %}
		<a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}, ({{ author.date_of_birth }}, {{author.date_of_death}})</a>
	      {% elif author.date_of_birth and not author.date_of_death %}
		<a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}, ({{ author.date_of_birth }}, - )</a>
	      {% elif not author.date_of_birth and not author.date_of_death %}
		<a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a>
	      {% elif not author.first_name and not author.date_of_birth and not author.date_of_death %}
		<a href="{{ author.get_absolute_url }}">{{ author.last_name }}</a>
      </li>
      {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>Aucun Auteur en Mémoire.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Titre: {{ book.title }}</h1>

  <p><strong>Auteur:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Résumé:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Catégorie:</strong> {{book.category.number}} - {{book.category.section.name}} / {{book.category.subsection.name}}</p>

  {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'd' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Date de retour:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Édition:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>SEQ:</strong> {{ copy.seq }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}  </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste de livres</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Aucun livre disponible en ibrairie.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_loan_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Prêt: {{ book_instance.book.title }}</h1>
  <p>Emprunteur: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Date de retour: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    <!-- Tout ce utilise post devrait avoir le 
      tag csrf_token, pour réduire les risques de
      sécurité -->
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Soumettre">
  </form>
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renouveler: {{ book_instance.book.title }}</h1>
  <p>Emprunteur: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Date de retour: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    <!-- Tout ce utilise post devrait avoir le 
      tag csrf_token, pour réduire les risques de
      sécurité -->
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Soumettre">
  </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Livres Sortis</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) - {{ bookinst.borrower}}
        {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renouveler</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Aucun livre emprunté.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Livres Empruntés</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Aucun livre emprunté.</p>
    {% endif %}
{% endblock %}